### PR TITLE
GH-421 Bump to `godot-cpp` 4.3-beta2

### LINKED ISSUE #421: Bump `godot-cpp` to 4.3-beta2
### Description

The `godot-cpp` 4.3-beta1 sync is commit sha 45be6d0bd4e6901d47d97bed2a18af0f76450eab.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by Naros**
Fixes #421

### CODE REVIEW

**Comment by Naros** [comment]
Build fails due to https://github.com/godotengine/godot-cpp/pull/1497

**Comment by Naros** [comment]
Applied to main (=2.1).

**Comment by aaronfranke** [comment]
@Naros For the `#if GODOT_VERSION >= 0x040400` guards in the "Add compile-time support for Godot 4.3.beta2+" commit, it doesn't work in the latest godot-cpp master with commits for Godot 4.4-dev2. However, it compiles if I change the `"version_minor"` in the API JSON from 4 back to 3.

I'm confused, what was the reason for introducing things like calls to `reset_state()` in a check for Godot 4.4+? Is there a PR somewhere to expose this function? At the moment it is not in the exposed API, so compiling just breaks:

<details>

```
src/script/serialization/binary_saver_instance.cpp:856:23: error: no member named 'set_edited' in 'godot::Resource'
  856 |             resource->set_edited(false);
      |             ~~~~~~~~~~^
1 error generated.
make[3]: *** [CMakeFiles/orchestrator.dir/src/script/serialization/binary_saver_instance.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
src/script/serialization/binary_loader_instance.cpp:1004:25: error: no member named 'reset_state' in 'godot::Resource'
 1004 |                 cached->reset_state();
      |                 ~~~~~~~~^
src/script/serialization/binary_loader_instance.cpp:1107:14: error: no member named 'set_edited' in 'godot::Resource'
 1107 |         res->set_edited(false);
      |         ~~~~~^
2 errors generated.
make[3]: *** [CMakeFiles/orchestrator.dir/src/script/serialization/binary_loader_instance.cpp.o] Error 1
src/script/serialization/text_loader_instance.cpp:186:26: error: no member named 'set_id_for_path' in 'godot::Resource'
  186 |                     res->set_id_for_path(_local_path, id);
      |                     ~~~~~^
src/script/serialization/text_loader_instance.cpp:658:22: error: no member named 'reset_state' in 'godot::Resource'
  658 |                 res->reset_state();
      |                 ~~~~~^
src/script/serialization/text_loader_instance.cpp:728:22: error: no member named 'set_path_cache' in 'godot::Resource'
  728 |                 res->set_path_cache(path);
      |                 ~~~~~^
src/script/serialization/text_loader_instance.cpp:823:14: error: no member named 'reset_state' in 'godot::Resource'
  823 |                     cache->reset_state();
      |                     ~~~~~~~^
src/script/serialization/text_loader_instance.cpp:887:18: error: no member named 'set_as_translation_remapped' in 'godot::Resource'
  887 |                                                 _resource->set_as_translation_remapped(_translation_remapped);
      |                                                 ~~~~~~~~~~~^
src/script/serialization/text_loader_instance.cpp:893:27: error: no member named 'set_path_cache' in 'godot::Resource'
  893 |                                     _resource->set_path_cache(_res_path);
      |                                     ~~~~~~~~~~~^
6 errors generated.
```

</details>

**Comment by Naros** [comment]
There is @aaronfranke, see https://github.com/godotengine/godot/pull/90969.  It's approved, I just need to address Remi's latest review comments, which I intended to follow-up on this weekend.

**Pull request merged**
